version: '3.9'
services:
  php-env:
    build: .
    volumes:
      - "./public_html:/var/www/html"
    ports:
      - 9000:80


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin_db:
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1